<?php
/**
 * Plugin Name: Taiwan Explorer Custom CSS & JS
 * Description: Reusable CSS/JavaScript snippets with per-page targeting and Taiwan Explorer shortcode.
 * Version: 2.0.0
 */
defined("ABSPATH") || exit;
function tec_init(){register_post_type("tec_code",["labels"=>["name"=>"Custom CSS & JS","add_new"=>"Add Snippet","add_new_item"=>"Add CSS/JS Snippet","edit_item"=>"Edit Snippet"],"public"=>false,"show_ui"=>true,"menu_icon"=>"dashicons-editor-code","supports"=>["title"],"show_in_menu"=>true]);} add_action("init","tec_init");
function tec_box(){add_meta_box("tec_settings","Snippet Settings","tec_box_html","tec_code","normal","high");} add_action("add_meta_boxes","tec_box");
function tec_box_html($p){wp_nonce_field("tec_save","tec_nonce");$type=get_post_meta($p->ID,"_tec_type",true)?:"css";$scope=get_post_meta($p->ID,"_tec_scope",true)?:"all";$ids=get_post_meta($p->ID,"_tec_ids",true);$code=get_post_meta($p->ID,"_tec_code",true);echo '<p>Type <select name="tec_type"><option value="css" '.selected($type,"css",false).'>CSS</option><option value="js" '.selected($type,"js",false).'>JavaScript</option></select></p><p>Load on <select name="tec_scope"><option value="all" '.selected($scope,"all",false).'>Entire site</option><option value="page" '.selected($scope,"page",false).'>Pages only</option><option value="post" '.selected($scope,"post",false).'>Posts only</option><option value="ids" '.selected($scope,"ids",false).'>Specific IDs</option></select></p><p>IDs <input name="tec_ids" value="'.esc_attr($ids).'" placeholder="123,456" style="width:80%"></p><p>Code</p><textarea name="tec_code" rows="20" style="width:100%;font-family:monospace">'.esc_textarea($code).'</textarea>';} 
function tec_save($id){if(!isset($_POST["tec_nonce"])||!wp_verify_nonce($_POST["tec_nonce"],"tec_save")||defined("DOING_AUTOSAVE")||get_post_type($id)!=="tec_code")return;foreach(["type","scope","ids","code"] as $k)if(isset($_POST["tec_".$k]))update_post_meta($id,"_tec_".$k,$k==="code"?wp_unslash($_POST["tec_".$k]):sanitize_text_field($_POST["tec_".$k]));} add_action("save_post","tec_save");
function tec_match($s,$ids){if($s==="all")return true;if($s==="page")return is_page();if($s==="post")return is_single();return $s==="ids"&&in_array((string)get_queried_object_id(),array_map("trim",explode(",",$ids)),true);} 
function tec_assets(){$q=new WP_Query(["post_type"=>"tec_code","post_status"=>"publish","posts_per_page"=>-1]);$css=$js="";while($q->have_posts()){$q->the_post();$id=get_the_ID();if(!tec_match(get_post_meta($id,"_tec_scope",true)?:"all",get_post_meta($id,"_tec_ids",true)))continue;$c=get_post_meta($id,"_tec_code",true);if(get_post_meta($id,"_tec_type",true)==="js")$js.="\n".$c;else $css.="\n".$c;}wp_reset_postdata();if($css){wp_register_style("tec-inline",false);wp_enqueue_style("tec-inline");wp_add_inline_style("tec-inline",$css);}if($js){wp_register_script("tec-inline",false,[],false,true);wp_enqueue_script("tec-inline");wp_add_inline_script("tec-inline",$js);}} add_action("wp_enqueue_scripts","tec_assets",99);
function tec_shortcode(){ $f=plugin_dir_path(__FILE__)."embed.html";return is_readable($f)?file_get_contents($f):"";} add_shortcode("taiwan_explorer","tec_shortcode");
